### ISSUE TITLE
ModuleNotFoundError: No module named 'retrying' (chore: release 2.1.0)

### ISSUE THREAD

**Issue by BatRaph** [google/slo-generator#193]
Hello,
  chore: release 2.1.0 (#188)

  I have installed slo-generator as explained and created files slo_config & shared_config
  I run command : `slo-generator compute -f slo/dynatrace.json -c backends/config.yaml --export`
  I have activate DEBUG mode and i got error
     **ModuleNotFoundError: No module named 'retrying' (ERROR1)**
     (import module in slo_generator/backends/dynatrace.py line 23)

   I have installed module retrying : pip install retrying
   i got error
      **Building wheel for retrying (setup.py) ... error (ERROR2)**

ERROR1
--------------
```
slo_generator.utils - DEBUG - No module named 'retrying'
Traceback (most recent call last):
  File "/home/laurendeau/project/slo-generator-project/venv/lib/python3.8/site-packages/slo_generator/utils.py", line 337, in import_dynamic
    return getattr(importlib.import_module(package), name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/laurendeau/project/slo-generator-project/venv/lib/python3.8/site-packages/slo_generator/backends/dynatrace.py", line 23, in <module>
    from retrying import retry
ModuleNotFoundError: No module named 'retrying'
```

ERROR2
--------------
```
(venv) VirtualBox:~/project/slo-generator-project$ pip install retrying
Collecting retrying
  Using cached retrying-1.3.3.tar.gz (10 kB)
Requirement already satisfied: six>=1.7.0 in ./venv/lib/python3.8/site-packages (from retrying) (1.16.0)
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/laurendeau/project/slo-generator-project/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxxveul1/retrying/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxxveul1/retrying/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rzdbqjil
       cwd: /tmp/pip-install-qxxveul1/retrying/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'

  ----------------------------------------
  ERROR: Failed building wheel for retrying
```

**Comment by ocervell** [comment]
Hi @BatRaph , could you please communicate the version of Python that you are using, and if you are running within a virtual environment ? 

To install the datadog backend, you need to run `pip install .[datadog]`. 

Could you let me know the output of this command ?
