### ISSUE TITLE
Running API in Kubernetes

### ISSUE THREAD

**Issue by djetelina** [google/slo-generator#208]
Hi, 
I wanted to run generator as an API inside of Kubernetes. The image I've built cause no issues when running as a job, so I figured getting the API running should provide no issues.

Unfortunately, API really likes to exit with the error code 255 right after starting. I did a few adjustments to try and find out what's causing it. Firstly, I added a debug line before function framework's `_cli` is invoked. The logs looked like this:

```
DEBUG mode is enabled. DEBUG=1
slo_generator.cli - DEBUG - Invoking functions framework
DEBUG mode is enabled. DEBUG=1
Stream closed EOF for monitoring/slo-generator-5bf7c8dd96-j8bdp (slo-generator)
```

Then I thought that it's probably Gunicorn doing funny things with PIDs and exiting, so I forwarded the DEBUG flag to functions framework, in order to run with Werkzeug. And this one has me baffled. These are the logs:

```
slo-generator-67df458cbf-6n559 DEBUG mode is enabled. DEBUG=1
slo-generator-67df458cbf-6n559 slo_generator.cli - DEBUG - Invoking functions framework
slo-generator-67df458cbf-6n559 DEBUG mode is enabled. DEBUG=1
slo-generator-67df458cbf-6n559  * Serving Flask app 'run_compute' (lazy loading)
slo-generator-67df458cbf-6n559  * Environment: production
slo-generator-67df458cbf-6n559    WARNING: This is a development server. Do not use it in a production deployment.
slo-generator-67df458cbf-6n559    Use a production WSGI server instead.
slo-generator-67df458cbf-6n559  * Debug mode: on
slo-generator-67df458cbf-6n559 werkzeug - WARNING -  * Running on all addresses.
slo-generator-67df458cbf-6n559    WARNING: This is a development server. Do not use it in a production deployment.
slo-generator-67df458cbf-6n559 werkzeug - INFO -  * Running on http://10.83.7.250:8080/ (Press CTRL+C to quit)
slo-generator-67df458cbf-6n559 werkzeug - INFO -  * Restarting with watchdog (inotify)
slo-generator-67df458cbf-6n559 DEBUG mode is enabled. DEBUG=1
slo-generator-67df458cbf-6n559 slo_generator.cli - DEBUG - Invoking functions framework
slo-generator-67df458cbf-6n559 Traceback (most recent call last):
slo-generator-67df458cbf-6n559   File "/usr/local/bin/slo-generator", line 8, in <module>
slo-generator-67df458cbf-6n559 DEBUG mode is enabled. DEBUG=1
slo-generator-67df458cbf-6n559     sys.exit(main())
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
slo-generator-67df458cbf-6n559     return self.main(*args, **kwargs)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
slo-generator-67df458cbf-6n559     rv = self.invoke(ctx)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
slo-generator-67df458cbf-6n559     return _process_result(sub_ctx.command.invoke(sub_ctx))
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
slo-generator-67df458cbf-6n559     return ctx.invoke(self.callback, **ctx.params)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
slo-generator-67df458cbf-6n559     return callback(*args, **kwargs)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
slo-generator-67df458cbf-6n559     return f(get_current_context(), *args, **kwargs)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/slo_generator/cli.py", line 153, in api
slo-generator-67df458cbf-6n559     ctx.invoke(_cli,
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
slo-generator-67df458cbf-6n559     return callback(*args, **kwargs)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli
slo-generator-67df458cbf-6n559     app = create_app(target, source, signature_type)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/functions_framework/__init__.py", line 292, in create_app
slo-generator-67df458cbf-6n559     function = _function_registry.get_user_function(source, source_module, target)
slo-generator-67df458cbf-6n559   File "/usr/local/lib/python3.9/site-packages/functions_framework/_function_registry.py", line 41, in get_user_function
slo-generator-67df458cbf-6n559     raise MissingTargetException(
slo-generator-67df458cbf-6n559 functions_framework.exceptions.MissingTargetException: File /usr/local/lib/python3.9/site-packages/slo_generator/api/main.py is expected to contain a function named http
Stream closed EOF for monitoring/slo-generator-67df458cbf-6n559 (slo-generator)
```

At first the app is created nicely (notice `Serving Flask app 'run_compute' (lazy loading)`), but then werkzeug triggers a reload (although I don't see why it would restart the entire command), which ends with the traceback you see, where it magically wants to run `http` as a target instead of signature type. I've went through functions framework's code a couple of times and I couldn't pinpoint anything that would be causing this. 

When I try to debug the container, running the command (`/usr/local/bin/slo-generator api --config /etc/config/config.yaml` works and runs properly, no exits). With debug & Flask I see the same issue.

Any guesses as to what could be causing the server to exit would be a huge help.

**Comment by djetelina** [comment]
The issue seems to be with `securityContext.readOnlyRootFilesystem`. I wish I knew which path the app is trying to write to, but I'll figure it out :)
