### ISSUE TITLE
Bug Backend cloud_monitoring slo Generator

### ISSUE THREAD

**Issue by florianmartineau** [google/slo-generator#296]
There are issue when I use the backend cloud_monitoring.py in particular the count function. When I have no value like good event, i have the following error :

 `Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slo_generator/backends/cloud_monitoring.py", line 227, in count
    return timeseries[0].points[0].value.int64_value`

In meanwhile for fix, I do that
`    @staticmethod
    def count(timeseries):
        """Count events in time series assuming it was aligned with ALIGN_SUM
        and reduced with REDUCE_SUM (default).

        Args:
            :obj:`monitoring_v3.TimeSeries`: Timeseries object.

        Returns:
            int: Event count.
        """
        try:
            return timeseries[0].points[0].value.int64_value
        #except (IndexError, AttributeError) as exception:
        #    LOGGER.debug(exception, exc_info=True)
        except:
            return NO_DATA  # no events in timeseries`

**Comment by lvaylet** [comment]
Hi @florianmartineau,

I am not sure why the current code is not catching this exception if it is indeed an `IndexError` as you reported in the emails we exchanged prior to this ticket:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slo_generator/backends/cloud_monitoring.py", line 227, in count
    return timeseries[0].points[0].value.int64_value
IndexError: list index out of range
```

I will try to reproduce this behavior. Just to be clear, does it occur when there are no **good** events, or when there are no **bad** events? No bad events is not a huge deal, meaning your SLI is currently 100%.

Also, could you share the SLO definition (redacting any confidential information), or at least the queries that caused this behavior?

**Comment by florianmartineau** [comment]
Hi,
My info in the slo :
`
 "spec": {
    "description": "MY APP",
    "error_budget_policy": "default",
    "backend": "cloud_monitoring/my-app",
    "method": "good_bad_ratio",
     "service_level_indicator": {
      "filter_good": "project=\"my-app\" AND metric.name=\"logging.googleapis.com/user/my-app\" AND metric.labels.type=\"JMS\" AND metric.labels.platform=\"ESLM\" AND metric.labels.available=1",
      "filter_bad": "project=\"my-app\" AND metric.name=\"logging.googleapis.com/user/my-app\" AND metric.labels.type=\"JMS\" AND metric.labels.platform=\"ESLM\" AND metric.labels.available=0"
    },
`
What i see in the log:
`slo_generator.backends.cloud_monitoring - DEBUG - ListTimeSeriesPager<unit: "1"
slo_generator.backends.cloud_monitoring - DEBUG - list index out of range

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slo_generator/backends/cloud_monitoring.py", line 226, in count
    return timeseries[0].points[0].value.int64_value
IndexError: list index out of range

slo_generator.backends.cloud_monitoring - DEBUG - Good events: -1 | Bad events: -1
slo_generator.report - DEBUG - My project | a.Last 1 hour | Backend response: (-1, -1)

OR 

"service_level_indicator": {
      "filter_good": "project=\"My project\" AND resource.labels.function_name=\"stream2kafka_violations\" AND metric.type=\"cloudfunctions.googleapis.com/function/execution_count\"",
      "filter_valid": "project=\"My project\" AND resource.labels.topic_id=\"ram-violations\" AND metric.type=\"pubsub.googleapis.com/topic/send_message_operation_count\""
    },

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slo_generator/backends/cloud_monitoring.py", line 226, in count
    return timeseries[0].points[0].value.int64_value
IndexError: list index out of range

slo_generator.report - DEBUG - My project | a.Last 1 hour | Backend response: (-1, 0)
`

It's seem not blocking but I have a lot traceback in my log.

**Comment by lvaylet** [comment]
Thanks a lot @florianmartineau for the detailed log outputs.

From what I can see, [the code](https://github.com/google/slo-generator/blob/c1351e065a3c0767ce8a50460c98f1ebb42326f6/slo_generator/backends/cloud_monitoring.py#L225-L229) behaves as expected:

```python
        try:
            return timeseries[0].points[0].value.int64_value
        except (IndexError, AttributeError) as exception:
            LOGGER.debug(exception, exc_info=True)
            return NO_DATA  # no events in timeseries
```

The `IndexError` exception is indeed caught by the `try...except` block, then logged with a `DEBUG` level (together with the stack trace you are seeing in the logs) and finally `NO_DATA` (i.e. `-1`) is returned (as shown again in the logs).

Does that make sense?

**Comment by florianmartineau** [comment]
Hello,
I think it would be better without the stacktrace because it's not an error (just no event in slo)
